[pytest]
python_files = tests/test_*.py
python_classes = *Tests
python_functions = test_*
pythonpath = .

# Configuración para pytest-asyncio
asyncio_mode = auto

# Configuración para pytest-env
# Carga las variables desde un archivo .env ubicado en el directorio de pruebas
env_files =
    tests/.env
