from typing import Any, Dict, List, Optional, Protocol

from models.user import User
from models.panel import Panel


class UserDAOProtocol(Protocol):
    def create_table(self) -> None: ...

    def create(self, user_id: int) -> Optional[User]: ...

    def find_or_create(self, user_id: int) -> Optional[User]: ...

    def find_by_id(self, user_id: int) -> Optional[User]: ...

    def update(self, user_id: int, **kwargs: Any) -> None: ...

    def get_leaderboard(self, limit: int = 10) -> List[User]: ...


class PoemDAOProtocol(Protocol):
    def create_table(self) -> None: ...

    def add_poem(self, content: str, author_id: int) -> None: ...

    def get_random_poem(self) -> Optional[str]: ...


class PanelDAOProtocol(Protocol):
    def create_table(self) -> None: ...

    def save_panel(self, guild_id: int, channel_id: int, message_id: int) -> None: ...

    def get_panel(self) -> Optional[Panel]: ...

    def clear_panel(self) -> None: ...
