import datetime
from typing import Any, Dict, Optional, Protocol

from models.user import User
from services.results import ServiceResult


class UserServiceProtocol(Protocol):
    def find_or_create(self, user_id: int) -> Optional[User]: ...

    def update_user(self, user_id: int, **fields: Any) -> None: ...

    def get_leaderboard(self, limit: int = 10) -> Any: ...

    def get_cooldown(self, last_time: Optional[datetime.datetime], seconds_needed: int) -> Optional[int]: ...

    def now_utc(self) -> datetime.datetime: ...


class EconomyServiceProtocol(Protocol):
    def work(self, user_id: int) -> Dict[str, Any]: ...

    def crime(self, user_id: int) -> Dict[str, Any]: ...

    def deposit(self, user_id: int, amount: int) -> Dict[str, Any]: ...

    def withdraw(self, user_id: int, amount: int) -> Dict[str, Any]: ...

    def donate(self, from_id: int, to_id: int, amount: int) -> Dict[str, Any]: ...

    def rob(self, from_id: int, to_id: int) -> Dict[str, Any]: ...


class LevelServiceProtocol(Protocol):
    def add_experience(self, user_id: int, xp_amount: int) -> Dict[str, Any]: ...

    def get_user_level_info(self, user_id: int) -> Dict[str, Any]: ...


class CasinoServiceProtocol(Protocol):
    def validate_bet(self, user_id: int, bet: int) -> ServiceResult[dict[str, Any]]: ...

    def collect_daily_reward(self, user_id: int) -> ServiceResult[dict[str, Any]]: ...

    def spin_slots(self, user_id: int, bet: int) -> ServiceResult[dict[str, Any]]: ...

    def coin_flip(self, user_id: int, bet: int, choice: str) -> ServiceResult[dict[str, Any]]: ...

    def settle_blackjack(self, user_id: int, player_value: int, dealer_value: int, bet: int, blackjack: bool = False) -> ServiceResult[dict[str, Any]]: ...

    def process_video_poker(self, user_id: int, bet: int, winnings: int) -> ServiceResult[dict[str, Any]]: ...

    def update_balance(self, user_id: int, new_balance: int) -> ServiceResult[dict[str, Any]]: ...

    def get_leaderboard(self, limit: int = 10) -> Any: ...


class ShopServiceProtocol(Protocol):
    def purchase_role(self, user_id: int, price: int) -> ServiceResult[Dict[str, int]]: ...


class HangmanServiceProtocol(Protocol):
    def reward_for_win(self, user_id: int, reward: int) -> ServiceResult[Dict[str, int]]: ...


class PoemServiceProtocol(Protocol):
    def get_poem(self) -> str: ...

    def add_poem(self, content: str, author_id: int) -> None: ...


class PanelServiceProtocol(Protocol):
    def save_panel(self, guild_id: int, channel_id: int, message_id: int) -> None: ...

    def get_panel(self) -> Optional[Dict[str, Any]]: ...

    def clear_panel(self) -> None: ...
